### ISSUE TITLE
Unable to get spans from this instrumentation

### ISSUE THREAD

**Issue by IvanovOleg** [mnadeem/opentelemetry-plugin-mssql#5]
Hello,
I've created a simple nodejs app that reads from the mssql database. I am able to get a result from the mssql query, but I see no spans.
index.js:
``` JS
const opentelemetry = require('@opentelemetry/api');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');
const { BasicTracerProvider, ConsoleSpanExporter, SimpleSpanProcessor } = require('@opentelemetry/tracing');
const { NodeTracerProvider } = require('@opentelemetry/node');
const { CollectorTraceExporter } = require('@opentelemetry/exporter-collector');
const { MssqlInstrumentation } = require('opentelemetry-instrumentation-mssql');
const sql = require('mssql');

const collectorOptions = {
  serviceName: 'db-service'
};

// Create and configure NodeTracerProvider
const traceProvider = new NodeTracerProvider({
  // be sure to disable old plugin
  plugins: {
    sequelize: { enabled: false, path: 'opentelemetry-plugin-mssql' }
  }
});

const exporter = new CollectorTraceExporter(collectorOptions);
traceProvider.addSpanProcessor(new SimpleSpanProcessor(exporter));
traceProvider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));

traceProvider.register()

registerInstrumentations({
  traceProvider,
  instrumentations: [
    new MssqlInstrumentation({
      // see under for available configuration
      ignoreOrphanedSpans: false
    })
  ]
});

const tracer = opentelemetry.trace.getTracer('db-service');

const config = {
  user: 'sa',
  password: 'Sjw2pBufpvGfh6*V',
  server: 'localhost',
  database: 'staff',
  options: {
    enableArithAbort: true
  }
}

sql.connect(config, function (err) {

  if (err) console.log(err);

  // create Request object
  var request = new sql.Request();

  // query to the database and get the records
  request.query('select * from employees', function (err, recordset) {

    if (err) console.log(err)

    // send records as a response
    console.log(recordset);

  });
});

```

```Json
{
  "name": "db",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opentelemetry/api": "^0.18.0",
    "@opentelemetry/exporter-collector": "^0.18.0",
    "@opentelemetry/instrumentation": "^0.18.0",
    "@opentelemetry/node": "^0.18.0",
    "@opentelemetry/tracing": "^0.18.0",
    "mssql": "^6.3.1",
    "opentelemetry-instrumentation-mssql": "^0.3.0"
  }
}

```

**Comment by mnadeem** [comment]
Refer this example https://github.com/mnadeem/nodejs-opentelemetry-tempo

it works

**Comment by IvanovOleg** [comment]
@mnadeem I've checked your example and see exactly the same telemetry configuration (except batch processor instead of simple processor.) It doesn't work in my app despite of the fact that I am following the example from the documentation.

**Comment by mnadeem** [comment]
Lets create a github project and share the link with me

**Comment by mnadeem** [comment]
Kind of curious why do we need 

````
const exporter = new CollectorTraceExporter(collectorOptions);
````

**Comment by IvanovOleg** [comment]
@mnadeem [nodejs-otel-sample](https://github.com/IvanovOleg/nodejs-otel-sample). I am interesting only in the db project. Producer and Consumer work fine.
`const exporter = new CollectorTraceExporter(collectorOptions);`
I am using the [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) to forward traces to jaeger

**Comment by mnadeem** [comment]
Lets create a simple project in github, preferably on lines of  https://github.com/mnadeem/nodejs-opentelemetry-tempo (Since it has MSSQL DB etc) and share the link

**Comment by IvanovOleg** [comment]
@mnadeem One question. Does this instrumentation create spans from scratch or it expects an active span to be created by the other component?

**Comment by mnadeem** [comment]
It expects active spans to be created by other component, simple one would be Express Instrumentation, this is the same behavior across all Open telemetry instrumentations 

https://github.com/mnadeem/nodejs-opentelemetry-tempo/blob/main/src/tracing.js#L22

**Comment by IvanovOleg** [comment]
@mnadeem kafkajs-instrumentation can create spans by itself or get span from the propagation

**Comment by mnadeem** [comment]
I was incorrect, It does create span if none exists https://github.com/mnadeem/opentelemetry-instrumentation-mssql/blob/master/src/mssql.ts#L141

However if we do it then how would you get hold of traceId, if you don't crate parent span

**Comment by IvanovOleg** [comment]
@mnadeem I've modified the **mssql.js** file and put **_console.log('name of the function')_** in each function. I got notification only from createPool and patchRequest. The rest of the code wasn't executed.
```JS
const opentelemetry = require('@opentelemetry/api');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');
const { BasicTracerProvider, ConsoleSpanExporter, SimpleSpanProcessor } = require('@opentelemetry/tracing');
const { NodeTracerProvider } = require('@opentelemetry/node');
const { CollectorTraceExporter } = require('@opentelemetry/exporter-collector');
const { MssqlInstrumentation } = require('opentelemetry-instrumentation-mssql');

const collectorOptions = {
  serviceName: 'db-service'
};

// Create and configure NodeTracerProvider
const traceProvider = new NodeTracerProvider({
  // be sure to disable old plugin
  plugins: {
    sequelize: { enabled: false, path: 'opentelemetry-plugin-mssql' }
  }
});

const exporter = new CollectorTraceExporter(collectorOptions);
traceProvider.addSpanProcessor(new SimpleSpanProcessor(exporter));
traceProvider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));

traceProvider.register();

registerInstrumentations({
  traceProvider,
  instrumentations: [
    new MssqlInstrumentation({
      // see under for available configuration
      ignoreOrphanedSpans: false
    })
  ]
});

const tracer = opentelemetry.trace.getTracer('db-service');

const sql = require('mssql');

const config = {
  user: 'sa',
  password: 'Sjw2pBufpvGfh6*V',
  server: 'localhost',
  database: 'staff',
  options: {
    enableArithAbort: true
  }
}

sql.on('error', err => {
  console.log(err);
})

sql.connect(config).then(pool => {
  // Query

  return pool.request()
    .input('input_parameter', sql.VarChar(50), 'Oleg')
    .query('select * from employees where name = @input_parameter')
}).then(result => {
  console.dir(result)
}).catch(err => {
  console.log(err);
});

```
```
PS C:\Users\dlj\Documents\nodejs-otel-sample\db> node .\index.js
createPool
patchRequest
{
  recordsets: [ [ [Object] ] ],
  recordset: [ { name: 'Oleg', last_name: 'Ivanov', position: 'devops' } ],
  output: {},
  rowsAffected: [ 1 ]
}
```

**Comment by mnadeem** [comment]
Refer this test case https://github.com/mnadeem/opentelemetry-instrumentation-mssql/blob/master/test/mssql.test.ts#L163 Spans are created.

Try creating parent span https://github.com/mnadeem/nodejs-opentelemetry-tempo/blob/main/src/server.js#L41  and see if it works.

It would be super helpful if you could create small project in github and demonstrate it, I fix any issues and create pull request

**Comment by IvanovOleg** [comment]
@mnadeem When I look at server.js file, I see a half-manual instrumentation, not an automatic one. I need to code a lot to make it work instead of just importing a library and get everything I need. If you take a look and producer and consumer app, that use kafka-js instrumentation, you will see that I just import the library in both apps and send the message. That instrumentation propagates a context between the apps and consumer's stuff appears as a child span without a single line of code

**Comment by mnadeem** [comment]
Appreciate if you could share the project, this would help me figure out what changes you are doing, and spot the not if any.

**Comment by IvanovOleg** [comment]
@mnadeem https://github.com/IvanovOleg/nodejs-otel-sample

**Comment by mnadeem** [comment]
````
sql.connect(config).then(pool => {
  // Query

  return new sql.Request(pool)
    //.input('input_parameter', sql.VarChar(50), 'Oleg')
    .query('SELECT 1 as number')
}).then(result => {
  console.dir(result)
}).catch(err => {
  console.log(err);
});
````

````
node index.js
{
  traceId: '36619977d05106e1542edb641f796b36',        
  parentId: undefined,
  name: 'SELECT',
  id: '1b3729cb96c57c26',
  kind: 2,
  timestamp: 1617385979244141,
  duration: 23149,
  attributes: {
    'db.system': 'mssql',
    'net.peer.host': 'localhost',
    'net.peer.port': 1433,
    'net.peer.address': 'jdbc:mysql://localhost:1433',
    'db.user': 'sa',
    'db.statement': 'SELECT 1 as number'
  },
  status: { code: 0 },
  events: []
}
{
  recordsets: [ [ [Object] ] ],
  recordset: [ { number: 1 } ],
  output: {},
  rowsAffected: [ 1 ]
}

````

Currently pool.query is bound and not pool.request. That instrumentation needs to be added
https://github.com/mnadeem/opentelemetry-instrumentation-mssql/blob/master/src/mssql.ts#L86

**Comment by mnadeem** [comment]
Thanks for opening this bug @IvanovOleg

**Comment by mnadeem** [comment]
Give me some time, I will provide instrumentation for `pool.request` as well, let me know if you have any other requirement as well

**Comment by IvanovOleg** [comment]
@mnadeem thanks!

**Comment by mnadeem** [comment]
@IvanovOleg 

As per https://stackoverflow.com/questions/49267785/types-mssql-cannot-find-connection-pool-type-defs-even-though-ts-is-looking-i **and** https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32326

`sql.connect(config)` is not exported globally. The correct way of doing it is


````
const connectToSqlServer = (async (): Promise<void> => {
  try {
    const pool = new sql.ConnectionPool(config);
    pool.connect().then(() => {
        const request = new sql.Request(pool);
        const result = await request.query(`select * from mock_people`);
        console.dir(result);
    });
  } catch (err) {
    console.error(err)
  }
})()
````

or

````
import * as sql from 'mssql';

async () => {
    try {
        const pool = new sql.ConnectionPool({
            server: 'localhost',
            user: 'username',
            password: 'password',
            database: 'database'
        });
        const value = 1;
        await pool.connect()
        const result = await pool.query(`select * from mytable where id = ${value}`)
        console.dir(result)
    } catch (err) {
        // ... error checks
    }
}
````

Further, I have added support for `pool.request().query()` https://github.com/mnadeem/opentelemetry-instrumentation-mssql/commit/f578a4cafb42feaaaa4c20f57af14089db599544

you should be able to use `0.3.1` soon for `pool.request().query()`

**Comment by mnadeem** [comment]
Version published https://www.npmjs.com/package/opentelemetry-instrumentation-mssql/v/0.3.1
